# Nom de l'action
name: Validation W3C

# Événements qui déclenchent l'action
on:
    push:
        branches: [crm, develop]
    pull_request:
        branches: [crm, develop]

# Jobs définissent les étapes de l'action
jobs:
    validation_w3c:
        runs-on: ubuntu-latest

        # Matrice de versions Node.js
        # pour exécuter l'action sur plusieurs versions
        strategy:
            matrix:
                node-version: [16.x, 18.x]

        # Étapes de l'action
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies
              run: npm install

            - name: Validate HTML
              id: validate
              run: npm run test
